### ISSUE TITLE
[Android] Crashes from branch shutdown-problems

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#983] opened 2017-08-09 08:13 UTC
Since I have switched to the shutdown-problems branch, I am seeing a bit less production crashes, it seems there are still 2 prevalent occurrences.

One is:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler com.mousebird.maply.LayerThread.addDelayedTask(java.lang.Runnable, long)' on a null object reference
       at com.mousebird.maply.LayoutLayer.scheduleUpdate(LayoutLayer.java:100)
       at com.mousebird.maply.LayoutLayer.startLayer(LayoutLayer.java:45)
       at com.mousebird.maply.LayerThread$5.run(LayerThread.java:260)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Another is:
```
Fatal Exception: java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
       at android.view.ThreadedRenderer.nDeleteProxy(ThreadedRenderer.java)
       at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:412)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
       at java.lang.Thread.run(Thread.java:818)
```

It would be great if they can be solved and the code can be merged into the main branch.

**Comment by mousebird** [comment] 2017-08-10 04:43
I'll put in guard code for the first one.

As for the second, I think we both [turned up this](https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin) before.  If this is related to that issue, I don't think there's a lot we can do.  It may be caused by working too long in the background, which could be due to threads still loading data when the app is backgrounded.

How much are you seeing that second one?

**Comment by jmcazaux** [comment] 2017-08-11 15:43
The second is fairly rare.
The first one is my top cause of crashes, so it would be good if this can be fixed and merged into the main branch.

**Comment by mousebird** [comment] 2017-08-14 03:42
I've put in guard code for the first one and merged in the shutdown-problems tree.
Reopen the second one if you want to register that bug.  It's too confusing to have multiple bugs in one Issue.

**Closed by mousebird** 2017-08-14 03:42 UTC
