### ISSUE TITLE
maplyViewController:didStopMoving:userMotion: not called on panning when map translation finishes with the finger still on the screen.

### ISSUE THREAD

**Issue by ambientlight** [mousebird/WhirlyGlobe#394] opened 2015-09-04 10:14 UTC
The Delegate method **maplyViewController:didStopMoving:**  not getting called on panning when map translation finishes with the finger still on the screen. (In the case when translation animation is still active, **didStopMoving** gets called correctly)
(DidStartMoving gets called in both cases)

(This probably is not the proper gesture for your gestureRecognizer, but then **didStartMoving** should not be getting called)

**Comment by mousebird** [comment] 2015-09-04 15:32
That is the intended behavior, since the gesture is still active, but I can see the confusion.

**Comment by ambientlight** [comment] 2015-09-04 15:58
But I mean, the fact that I remove finger after translation is done is not getting recognized.

the delegate call is only generated if finger is removed before the translation animation finishes. In opposite case - no delegate call.

**Comment by mousebird** [comment] 2015-09-04 16:55
I'm not sure I follow.  Can you describe the gesture again?  I'd like to try and duplicate this.

**Comment by ambientlight** [comment] 2015-09-04 17:15
press and hold the finger(mouse) -> move it slightly -> stop moving it -> release finger(mouse). (to make sure you are not getting a swipe gesture, so at the point you are releasing your finger, the map translation is not animating)

**Comment by rghosh0** [comment] 2017-02-21 16:22
I can't reproduce this.

I tried using the simulator (because releasing the mouse-button without movement is easier than releasing a finger from the touch-screen without movement).

But in that case, even when the globe has stopped and I release the mouse-button without any mouse motion, there is suddenly a small motion in the movement of the previous mouse motion.  So unless that is a problem, I think this issue no longer applies.

**Comment by mousebird** [comment] 2017-05-24 21:14
I believe this is now fixed.

**Closed by mousebird** 2017-05-24 21:14 UTC
